name: tracelock-local

services:
  gateway:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    environment:
      TRACELOCK_SERVICE_NAME: tracelock-gateway
      TRACELOCK_SERVICE_ROLE: gateway
      TRACELOCK_ENVIRONMENT: local
    ports:
      - "8000:8000"
    networks:
      - workload-path
      - egress-path
      - control-path

  workload:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    environment:
      TRACELOCK_SERVICE_NAME: analytics-workload
      TRACELOCK_SERVICE_ROLE: workload
      TRACELOCK_ENVIRONMENT: local
    networks:
      - workload-path
    depends_on:
      - gateway

  control-plane:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    environment:
      TRACELOCK_SERVICE_NAME: tracelock-control-plane
      TRACELOCK_SERVICE_ROLE: control-plane
      TRACELOCK_ENVIRONMENT: local
    networks:
      - control-path
    depends_on:
      - gateway

  fake-destination:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    environment:
      TRACELOCK_SERVICE_NAME: external-webhook
      TRACELOCK_SERVICE_ROLE: fake-destination
      TRACELOCK_ENVIRONMENT: local
    networks:
      - egress-path
    depends_on:
      - gateway

networks:
  workload-path:
    internal: true
  egress-path:
    internal: true
  control-path:
    internal: true
